name: Mutation testing (MutPy)

# on:
#   workflow_dispatch:
#   push:
#     paths:
#       - "Lab1/**"
#       - ".github/workflows/mutpy.yml"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Lab1/**"
      - ".github/workflows/lab1-*.yml"

jobs:
  mutpy:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: Lab1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r Lab1/requirements-dev.txt

      - name: "Sanity: run unit tests"
        run: |
          pytest -q -c Lab1/pytest.ini Lab1/tests

      - name: Run MutPy (pytest runner)
        env:
          PYTHONPATH: Lab1
        run: |
          mut.py \
            --runner pytest \
            --target calc \
            --unit-test tests \
            --path Lab1 \
            --report Lab1/mutpy_results.txt \
            --report-html Lab1/mutpy_html

          echo "---- MUTPY TEXT REPORT (tail) ----"
          tail -n 200 Lab1/mutpy_results.txt
          test -s Lab1/mutpy_results.txt

      - name: Upload MutPy reports
        uses: actions/upload-artifact@v4
        with:
          name: mutpy-reports
          path: |
            Lab1/mutpy_results.txt
            Lab1/mutpy_html
