name: Mutation testing (mutmut)

on:
  workflow_dispatch:
  push:
    paths:
      - "Lab1/**"
      - ".mutmut.ini"
      - ".github/workflows/mutmut.yml"

jobs:
  mutmut:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: Lab1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Lab1/requirements-dev.txt mutmut

      - name: Run unit tests
        run: |
          pytest -q -c Lab1/pytest.ini Lab1/tests

      - name: Run mutation tests (mutmut)
        run: |
          mutmut run
          mutmut results | tee mutmut_results.txt

      - name: Upload mutation report
        uses: actions/upload-artifact@v4
        with:
          name: mutmut-results
          path: mutmut_results.txt
